name: PHP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "php"
    strategy:
      matrix:
        dependencies:
          - "lowest"
          - "highest"
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
        env:
          update: true
      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            php/vendor
          key: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}"
          restore-keys: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}"
      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --no-interaction --no-progress"
      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --no-interaction --no-progress"
      - name: "PHPStan"
        run: "vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=-1"
      - name: "Tests"
        run: "vendor/bin/pest"


  sync-downstream:
    runs-on: ubuntu-latest
    name: Update downstream repository
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          repo: 'stefandanaita/truelayer-signing-php'
          path: 'php'
          deploy_key: ${{ secrets.DOWNSTREAM_GITHUB_DEPLOY_KEY }}
          tag: true
          force: true
  # split:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: "truelayer-signing"
  #   steps:
  #     - name: "Checkout"
  #       uses: actions/checkout@v2
  #       with:
  #         path: "truelayer-signing"
  #         fetch-depth: 0
  #     - name: "Download Splitsh Lite binary"
  #       run: |
  #         mkdir -p $GITHUB_WORKSPACE/bin
  #         wget https://github.com/splitsh/lite/releases/download/v1.0.1/lite_linux_amd64.tar.gz -P $GITHUB_WORKSPACE/bin
  #         tar -zxpf $GITHUB_WORKSPACE/bin/lite_linux_amd64.tar.gz --directory $GITHUB_WORKSPACE/bin
  #         rm $GITHUB_WORKSPACE/bin/lite_linux_amd64.tar.gz
  #         chmod +x $GITHUB_WORKSPACE/bin/splitsh-lite
  #     - name: "Add readonly repository remote"
  #       run: git remote add php https://github.com/stefandanaita/truelayer-signing-php
  #     - name: "Split the php directory"
  #       run: |
  #         SHA1=`$GITHUB_WORKSPACE/bin/splitsh-lite --path=$GITHUB_WORKSPACE/truelayer-signing --prefix=php`
  #         git push php "$SHA1:refs/heads/main" -f

